# Grunt aliases
---
# Build everything
build:
  - 'build:css'
  - 'build:images'
  - 'build:js'
  - 'build:i18n'
# Build CSS for production
'build:css':
  - 'autoprefixer'
  - 'wpcss'
  - 'cssmin'
# Build JavaScript from assets to production
'build:js':
  - 'uglify'
# Optimise images from source to production
'build:images':
  - 'imagemin'
# Build internationalisation features
'build:i18n':
  - 'addtextdomain'
# Check health of the project
check:
  - 'jsonlint'
  - 'eslint'
  - 'phplint'
  - 'phpcs'
  - 'checktextdomain'
# Default task
default:
  - build
