# Grunt aliases
---
'build':
  - 'build:css'
  - 'build:js'
  - 'makepot'

# Build a distribution zip file
'artifact':
  - 'shell:composer-install-production'
  # Build like we normally would
  - 'release'
  # Remove build folder
  - 'clean:artifact'
  # Copy only the relevant files to the folder
  - 'copy:artifact'
  # Create a zip file
  - 'compress:artifact'
  - 'restore-environment-after-artifact'

# Get the project ready for release
# Note that using this command triggers some global variables to be different from if you use simply `build`
release:
  - build

# Update all versions except the stable tag
'update-version-trunk':
  - 'update-version:pluginFile'
  - 'update-version:initializer'

'clean:build-assets':
  - 'clean:build-assets-js'
  - 'clean:build-assets-css'

# Deploy current state to WordPress.org trunk
'deploy:trunk':
  - 'update-version-trunk'
  - 'artifact'
  - 'wp_deploy:trunk'

# Deploy current state to WordPress.org master
'deploy:master':
  - 'update-version'
  - 'artifact'
  - 'wp_deploy:master'

'restore-environment-after-artifact':
  - 'shell:composer-reset-config'
  - 'shell:composer-reset-lock'
  - 'shell:composer-install-dev'
