---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
    exclude_fingerprints:
        - bbf999adfc53fc4c2dfe341d3f3b9372
  fixme:
    enabled: true
  phpmd:
    enabled: true
    exclude_fingerprints:
        - 9e2c003157b8327cc28f5dfdfcf54370
        - e48a303e91de028bf180064acb880dbb
        - cd6e7ec8dd32e2bc82ae64126c0e3b03
        - 2c4b9c7656fb60d4a015b73a221fadaf
    config:
      rulesets: "phpmd.xml"
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
exclude_paths:
- grunt/*
- grunt/**/*