os: linux
language: php

branches:
  only:
    - master
    - trunk
    - /^release\/*/
    - /^hotfix\/\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  fast_finish: true
  include:
    - php: 7.4
      env: CHECK=1 TRAVIS_NODE_VERSION=node

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - node_modules

before_install:
  - if [[ "$COVERAGE" != "1" ]]; then phpenv config-rm xdebug.ini || echo 'No xdebug config.'; fi
  - |
    if [[ "$CHECK" == "1" ]]; then
      nvm install $TRAVIS_NODE_VERSION
      curl -o- -L https://yarnpkg.com/install.sh | bash
      export PATH=$HOME/.yarn/bin:$PATH
    fi

install:
  - |
    if [[ "$CHECK" == "1" ]]; then
      composer install --no-interaction
    fi
  - |
    if [[ "$CHECK" == "1" ]]; then
      yarn global add grunt-cli
      yarn install
    fi

before_script:
  - export -f travis_fold
  - export -f travis_time_start
  - export -f travis_time_finish
  - phpenv versions
  - php --version
  - php -m
  - curl --version
  - git --version
  - svn --version
  - locale -a

script:
  # GRUNT Tasks
  - |
    if [[ "$CHECK" == "1" ]]; then
      travis_fold start "Grunt.check" && travis_time_start
      grunt check
      travis_time_finish && travis_fold end "Grunt.check"
    fi
