language: php
dist: trusty

branches:
  only:
    - master
    - trunk
    - /^release\/*/
    - /^hotfix\/\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  fast_finish: true
  include:
    - php: 7.4
      env: PHPLINT=1 CHECK=1 PHPCS=1 TRAVIS_NODE_VERSION=node
    - php: 5.6
      env: PHPLINT=1
    - php: "nightly"
      env: PHPLINT=1
  allow_failures:
    # Allow failures for unstable builds.
    - php: "nightly"
      env: PHPLINT=1

cache:
  yarn: true
  directories:
    - .cache
    - $HOME/.composer/cache
    - node_modules

before_install:
  - if [[ "$COVERAGE" != "1" ]]; then phpenv config-rm xdebug.ini || echo 'No xdebug config.'; fi
  - |
    if [[ "$CHECK" == "1" ]]; then
      nvm install $TRAVIS_NODE_VERSION
      curl -o- -L https://yarnpkg.com/install.sh | bash
      export PATH=$HOME/.yarn/bin:$PATH
    fi

install:
  - |
    if [[ $TRAVIS_PHP_VERSION == "nightly" && "$PHPLINT" == "1" ]]; then
      composer install --no-interaction --ignore-platform-reqs
    elif [[ "$CHECK" == "1" || "$PHPCS" == "1" || "$PHPLINT" == "1" ]]; then
      composer install --no-interaction
    fi
  - |
    if [[ "$CHECK" == "1" ]]; then
      yarn global add grunt-cli
      yarn install
    fi

before_script:
  - export -f travis_fold
  - export -f travis_time_start
  - export -f travis_time_finish
  - mysql --version
  - phpenv versions
  - php --version
  - php -m
  - curl --version
  - git --version
  - svn --version
  - locale -a

script:
  # PHP Linting
  - |
    if [[ "$PHPLINT" == "1" ]]; then
      travis_fold start "PHP.check" && travis_time_start
      composer lint
      travis_time_finish && travis_fold end "PHP.check"
    fi
  # GRUNT Tasks
  - |
    if [[ "$CHECK" == "1" ]]; then
      travis_fold start "Grunt.check" && travis_time_start
      grunt check
      travis_time_finish && travis_fold end "Grunt.check"
    fi
  # PHPCS
  - if [[ "$PHPCS" == "1" ]]; then composer check-cs;fi
  # Validate the composer.json file.
  # @link https://getcomposer.org/doc/03-cli.md#validate
  - if [[ $TRAVIS_PHP_VERSION == "5.6" || $TRAVIS_PHP_VERSION == "7.4" ]]; then composer validate --no-check-all; fi
